// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Add(arg1:main.AddRequest):Promise<Array<string>>;

export function Cancel(arg1:string):Promise<void>;

export function ClearFinished():Promise<void>;

export function GetConfig():Promise<main.Config>;

export function Info():Promise<main.AppInfo>;

export function List():Promise<Array<main.Item>>;

export function Networks():Promise<Array<main.NetInfo>>;

export function OpenDir(arg1:string):Promise<void>;

export function Pause(arg1:string):Promise<void>;

export function PickDir(arg1:string):Promise<string>;

export function Remove(arg1:string):Promise<void>;

export function Resume(arg1:string):Promise<void>;

export function Reveal(arg1:string):Promise<void>;

export function SetConfig(arg1:main.Config):Promise<main.Config>;

export function TestNetworks(arg1:Array<string>):Promise<Array<main.TestResult>>;
