// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['main']['App']['Add'](arg1);
}

export function Cancel(arg1) {
  return window['go']['main']['App']['Cancel'](arg1);
}

export function ClearFinished() {
  return window['go']['main']['App']['ClearFinished']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Info() {
  return window['go']['main']['App']['Info']();
}

export function List() {
  return window['go']['main']['App']['List']();
}

export function Networks() {
  return window['go']['main']['App']['Networks']();
}

export function OpenDir(arg1) {
  return window['go']['main']['App']['OpenDir'](arg1);
}

export function Pause(arg1) {
  return window['go']['main']['App']['Pause'](arg1);
}

export function PickDir(arg1) {
  return window['go']['main']['App']['PickDir'](arg1);
}

export function Remove(arg1) {
  return window['go']['main']['App']['Remove'](arg1);
}

export function Resume(arg1) {
  return window['go']['main']['App']['Resume'](arg1);
}

export function Reveal(arg1) {
  return window['go']['main']['App']['Reveal'](arg1);
}

export function SetConfig(arg1) {
  return window['go']['main']['App']['SetConfig'](arg1);
}

export function TestNetworks(arg1) {
  return window['go']['main']['App']['TestNetworks'](arg1);
}
